### ISSUE TITLE
Consider linking to repo from published crate

### ISSUE THREAD

**Issue by Qqwy** [AlyssaRoseDev/stele#1]
It is possible to link to the GitHub repository from within crates.io and published docs.rs documentation by adding the following to the `Cargo.toml`:

```toml

repository = "https://github.com/AlyssaRoseDev/stele"
```

This will make it easier for people to find the repository to e.g. report bugs or contribute PRs 😊

**Comment by AlyssaRoseDev** [comment]
Added in 0.3!
